### ISSUE TITLE
Revise the plugin with the events and handlers actually used in seekBar

### ISSUE THREAD

**Issue by borzaka** [rsadwick/videojs-disable-progress#5]
For example I think this is missing:
```js

//disable
player.controlBar.progressControl.seekBar.off("mouseup");
player.controlBar.progressControl.seekBar.off("touchend");

//enable
player.controlBar.progressControl.seekBar.on("mouseup",  player.controlBar.progressControl.seekBar.handleMouseUp);
player.controlBar.progressControl.seekBar.on("touchend", player.controlBar.progressControl.seekBar.handleMouseUp);

```

And this handleClick function is not exists in the [seekBar](https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/seek-bar.js):
```js
player.controlBar.progressControl.seekBar.on("click", player.controlBar.progressControl.seekBar.handleClick);
```

And maybe `click` event is not even used? Maybe there's more.

5.x and 6.x has no difference in events and handlers in seekBar.

**Comment by rsadwick** [comment]
sorry so late on this but if you fixed it, you can submit a PR thanks!
