### ISSUE TITLE
Still compatible with videojs 7 ?

### ISSUE THREAD

**Issue by Valoute-GS** [rsadwick/videojs-disable-progress#9]
Hello I'v tried your pluggin but in vain, even try to modify a bit your code to update it ton videojs 7 but nothing work 
Maybe I don't set the pluggin the right way

my .html
```html
<!doctype html>

<html lang="fr">

<head>
  <!-- meta -->
  <meta charset="utf-8">
  <title>test</title>

  <link href="css/styles.css" rel="stylesheet">
  <link href="css/video-js.css" rel="stylesheet">

</head>

<body>
  <video id='myvideo' class='video-js vjs-default-skin vjs-big-play-centered' preload="auto"
    oncontextmenu="return false" width="100%" height="100%" controls
    data-setup='{ "aspectRatio":"16:9", "fluid": true}'>
    <!--ontimeupdate="checkChapter()"-->
    <source src='vid/rg.mp4' type='video/mp4'>
  </video>

</body>
<script src='js/video.js'></script>
<script src='js/videojs.disableProgress.js'></script>
<script src="js/script.js"></script>

</html>
```

.js
```js
//change vjs to videojs
videojs.plugin('disableProgress', disableProgress);
var enabled = false;
var myPlayer = videojs('myvideo');
myPlayer.disableProgress.disable();
```
Got this
```
script.js: Uncaught ReferenceError: disableProgress is not defined
```

**Comment by rsadwick** [comment]
It looks like this plugin isn't compatible.  I tried with the latest stable version 7.6.0.  I'll have to see what changed before starting on a fix.

**Comment by yixiaohero** [comment]
I temporarily added some code to temporarily achieve the purpose.
disable:
`player.controlBar.progressControl.off("mousedown");
player.controlBar.progressControl.off("mouseup");
player.controlBar.progressControl.off("touchstart");
player.controlBar.progressControl.off("touchend");`
enable:
`
player.controlBar.progressControl.on("mousedown",player.controlBar.progressControl.handleMouseDown);	            player.controlBar.progressControl.on("mouseup",player.controlBar.progressControl.handleMouseUp);	            player.controlBar.progressControl.on("touchstart",player.controlBar.progressControl.handleMouseDown);            player.controlBar.progressControl.on("touchend",player.controlBar.progressControl.handleMouseUp);`

**Comment by rsadwick** [comment]
Thanks.  I still haven't been able to get to this and check out what's changed with videojs plugins.  This weekend I'll take a look and see what needs to be changed.

**Comment by fringemedia** [comment]
Anyone else looking for this in videoJS 7, you can disable the seek bar using :
player.controlBar.progressControl.disable()

**Comment by rason560** [comment]
> Anyone else looking for this in videoJS 7, you can disable the seek bar using :
> player.controlBar.progressControl.disable()

Great, it works! thanks so much
